### ISSUE TITLE
Implement Drupal-like roles and permissions system

### ISSUE THREAD

**Issue by alberto56** [dcycle/starterkit-node#86]
Currently users can be "authenticated" or "anonymous", as we can see in app/config/versioned.yml

I'd like to implement a new module called "dashboardUI", which will *not do anything for the moment*

The module will define a route which will be called dashboardUI which will load a message which says "This is where the admin dashboard will be"

In ./app/config/versioned.yml, for the routes, we will change the way they are organized, so that each route is associated with a permission, not a role, and then roles as associated with permissions, like this:

```
modules:
  ./webAuth/index.js:
    roles:
      authenticated:
        - "view authenticated routes"
      administrator:
        - "view administrative dashboard"
      anonymous:
        - "view anonymous routes"
    routes:
      - route: chat
        verb: get
        permission: "view authenticated routes"
      - route: chatApi
        verb: get
        permission: "view authenticated routes"
      - route: chatApi
        verb: post
        permission: "view authenticated routes"
...
      - route: dashboardUI
        verb: get
        permission: "view administrative dashboard"

```

When the system is first created, the "admin" user has the roles "authenticated" and "administrator", but users created using ./scripts/reset-password.sh some-user will on only have the role "authenticated".

Those users will not be able to see the admin dashboard page.

This system will work a lot like Drupal's system.

Roles are currently hard-coded in app/code/webAuth/index.js (authenticated, anonymous, authenticatedJson), but we want to now define them in the config.

It will be possible to have a function which shows you the roles of a given user, such as app.c(''accountFramework").accountHasPermission("view administrative dashboard") which will return true if *at least one of the merged accounts* has a role which has the permission  "view administrative dashboard".
